---
# update gitolte configuration/setup
- name: gitolite setup
  tags: gitolite
  sudo: yes
  sudo_user: "{{ gitolite_user_name }}"
  action: command {{ gitolite_install_dir }}/gitolite setup
    chdir={{ gitolite_user_home }}


# httpd server
- name: service restart httpd
  tags: gitolite_httpd
  service:
    state=restarted
    name={{ gitolite_httpd_service }}


# git-daemon service
- name: sv restart git-daemon
  tags: gitolite_gitdaemon
  shell: sv restart {{ gitolite_gitdaemon_sv }}


 # apache server for gitweb
- name: service restart gitweb
  tags: gitolite_gitweb
  service:
    state=restarted
    name={{ gitolite_gitweb_service }}
