#!/bin/bash
#set -xv
#exec 2>/tmp/uml.$$
/bin/sed -e 's/ä/\&auml;/g' \
         -e 's/ö/\&ouml;/g' \
         -e 's/ü/\&uuml;/g' \
         -e 's/ß/\&szlig;/g'\
         -e 's/Ä/\&Auml;/g' \
         -e 's/Ö/\&Ouml;/g' \
         -e 's/Ü/\&Uuml;/g'
